services:
  api:
    image: ${DOCKERHUB_USERNAME}/sentinel-backend:latest
    container_name: sentinel_api
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - sentinel_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db:
    image: postgres:15-alpine
    container_name: sentinel_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sentinel_network
    # Pas de ports exposés, accès via tunnel SSH sur le port 5432

  redis:
    image: redis/redis-stack-server:latest
    container_name: sentinel_redis
    restart: always
    networks:
      - sentinel_network
    # Pas de ports exposés, accès via tunnel SSH sur le port 6379

networks:
  sentinel_network:
    external: true

volumes:
  postgres_data:
