services:
  api:
    build: .
    image: sentinel-api:local
    container_name: sentinel_api
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: npm run start:dev
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - sentinel_network

  db:
    image: postgres:15-alpine
    container_name: sentinel_db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sentinel_network

  redis:
    image: redis/redis-stack-server:7.2.0-v6
    container_name: sentinel_redis
    ports:
      - "6379:6379"
    networks:
      - sentinel_network

  loki:
    image: grafana/loki:latest
    container_name: sentinel_loki
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki_data:/loki
    networks:
      - sentinel_network

  promtail:
    image: grafana/promtail:latest
    container_name: sentinel_promtail
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./infrastructure/monitoring/promtail-config.yaml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yaml
    networks:
      - sentinel_network

  grafana:
    image: grafana/grafana:latest
    container_name: sentinel_grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./infrastructure/monitoring/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - sentinel_network

networks:
  sentinel_network:
    driver: bridge

volumes:
  postgres_data:
  loki_data:
  grafana_data: